# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
  - ".cache/pip"
  - venv/
before_script:
- python -V
- apt-get update -y
- apt-get install gzip brotli -y
- python -m venv venv
- source venv/bin/activate
- pip install poetry
- poetry install
pages:
  script:
  - cd docs
  - python main.py build
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|xml\|png\)$'
    -exec gzip -f -k {} \;
  - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|xml\)$' -exec
    brotli -f -k {} \;
  - mv public ../public
  artifacts:
    paths:
    - public
  rules:
  - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
stages:
- test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
